/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Tanvin
 */
public class FastCash extends javax.swing.JFrame {

    /**
     * Creates new form FastCash
     */
    public FastCash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        accNo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        tk1000 = new javax.swing.JButton();
        tk100 = new javax.swing.JButton();
        tk5000 = new javax.swing.JButton();
        tk500 = new javax.swing.JButton();
        tk10000 = new javax.swing.JButton();
        tk2000 = new javax.swing.JButton();
        amount = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        Confirm = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ATM.gif"))); // NOI18N
        jLabel1.setText("Virtual ATM");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Batang", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/money.gif"))); // NOI18N
        jLabel2.setText("Fast Cash");

        name.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/account.gif"))); // NOI18N
        name.setText("Mr. Borolok");
        name.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Account No:");

        accNo.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        accNo.setForeground(new java.awt.Color(255, 255, 255));
        accNo.setText("12345678910");

        jPanel4.setBackground(new java.awt.Color(24, 78, 99));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(0, 51, 255), new java.awt.Color(0, 51, 255), new java.awt.Color(51, 102, 255)));

        tk1000.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        tk1000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/coin.gif"))); // NOI18N
        tk1000.setText("TK 1000");
        tk1000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tk1000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tk1000MouseClicked(evt);
            }
        });
        tk1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tk1000ActionPerformed(evt);
            }
        });

        tk100.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        tk100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/coin.gif"))); // NOI18N
        tk100.setText("TK 100");
        tk100.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tk100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tk100MouseClicked(evt);
            }
        });
        tk100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tk100ActionPerformed(evt);
            }
        });

        tk5000.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        tk5000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/coin.gif"))); // NOI18N
        tk5000.setText("TK 5000");
        tk5000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tk5000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tk5000MouseClicked(evt);
            }
        });
        tk5000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tk5000ActionPerformed(evt);
            }
        });

        tk500.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        tk500.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/coin.gif"))); // NOI18N
        tk500.setText("TK 500");
        tk500.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tk500.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tk500MouseClicked(evt);
            }
        });
        tk500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tk500ActionPerformed(evt);
            }
        });

        tk10000.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        tk10000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/coin.gif"))); // NOI18N
        tk10000.setText("TK 10000");
        tk10000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tk10000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tk10000MouseClicked(evt);
            }
        });
        tk10000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tk10000ActionPerformed(evt);
            }
        });

        tk2000.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        tk2000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/coin.gif"))); // NOI18N
        tk2000.setText("TK 2000");
        tk2000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tk2000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tk2000MouseClicked(evt);
            }
        });
        tk2000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tk2000ActionPerformed(evt);
            }
        });

        amount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        amount.setForeground(new java.awt.Color(255, 255, 255));
        amount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amount.setText("Balance");
        amount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 0), new java.awt.Color(51, 102, 0), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 153, 0)));
        amount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tk1000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tk100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tk5000, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tk10000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tk2000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tk500, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tk500, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tk100))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tk1000)
                        .addComponent(tk2000)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tk5000)
                    .addComponent(tk10000))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("a Astro Space", 0, 14)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.gif"))); // NOI18N
        back.setText("Back");
        back.setName(""); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        Confirm.setBackground(new java.awt.Color(255, 255, 255));
        Confirm.setFont(new java.awt.Font("a Astro Space", 0, 13)); // NOI18N
        Confirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/confirm.gif"))); // NOI18N
        Confirm.setText(" CONFIRM");
        Confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmMouseClicked(evt);
            }
        });
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(accNo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(Confirm)))
                .addContainerGap(119, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accNo)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Confirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tk1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tk1000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tk1000ActionPerformed

    private void tk100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tk100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tk100ActionPerformed

    private void tk5000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tk5000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tk5000ActionPerformed

    private void tk500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tk500ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tk500ActionPerformed

    private void tk10000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tk10000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tk10000ActionPerformed

    private void tk2000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tk2000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tk2000ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmActionPerformed

    private void tk100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tk100MouseClicked
        // TODO add your handling code here:

        flag = 1;
        if (con == false) {
            tk100.setBackground(Color.green);
            con = true;
            fastAmount = "100.0";

            tk500.setBackground(Color.white);
            tk1000.setBackground(Color.white);
            tk2000.setBackground(Color.white);
            tk5000.setBackground(Color.white);
            tk10000.setBackground(Color.white);

        } else {
            tk100.setBackground(Color.white);
            con = false;
            fastAmount = "0";
        }

    }//GEN-LAST:event_tk100MouseClicked

    private void tk500MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tk500MouseClicked
        // TODO add your handling code here:
        if (con == false) {
            tk500.setBackground(Color.green);
            con = true;
            fastAmount = "500.0";
            tk100.setBackground(Color.white);

            tk1000.setBackground(Color.white);
            tk2000.setBackground(Color.white);
            tk5000.setBackground(Color.white);
            tk10000.setBackground(Color.white);
        } else {
            tk500.setBackground(Color.white);
            con = false;
            fastAmount = "0";
        }
    }//GEN-LAST:event_tk500MouseClicked

    private void tk1000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tk1000MouseClicked
        // TODO add your handling code here:
        if (con == false) {
            tk1000.setBackground(Color.green);
            con = true;
            fastAmount = "1000.0";
            tk100.setBackground(Color.white);
            tk500.setBackground(Color.white);

            tk2000.setBackground(Color.white);
            tk5000.setBackground(Color.white);
            tk10000.setBackground(Color.white);
        } else {
            tk1000.setBackground(Color.white);
            con = false;
            fastAmount = "0";
        }
    }//GEN-LAST:event_tk1000MouseClicked

    private void tk2000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tk2000MouseClicked
        // TODO add your handling code here:
        if (con == false) {
            tk2000.setBackground(Color.green);
            con = true;
            fastAmount = "2000.0";
            tk100.setBackground(Color.white);
            tk500.setBackground(Color.white);
            tk1000.setBackground(Color.white);

            tk5000.setBackground(Color.white);
            tk10000.setBackground(Color.white);
        } else {
            tk2000.setBackground(Color.white);
            con = false;
            fastAmount = "0";
        }
    }//GEN-LAST:event_tk2000MouseClicked

    private void tk5000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tk5000MouseClicked
        // TODO add your handling code here:
        if (con == false) {
            tk5000.setBackground(Color.green);
            con = true;
            fastAmount = "5000.0";
            tk100.setBackground(Color.white);
            tk500.setBackground(Color.white);
            tk1000.setBackground(Color.white);
            tk2000.setBackground(Color.white);

            tk10000.setBackground(Color.white);
        } else {
            tk5000.setBackground(Color.white);
            con = false;
            fastAmount = "0";
        }
    }//GEN-LAST:event_tk5000MouseClicked

    private void tk10000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tk10000MouseClicked
        // TODO add your handling code here:
        if (con == false) {
            tk10000.setBackground(Color.green);
            con = true;
            fastAmount = "10000.0";
            tk100.setBackground(Color.white);
            tk500.setBackground(Color.white);
            tk1000.setBackground(Color.white);
            tk2000.setBackground(Color.white);
            tk5000.setBackground(Color.white);

        } else {
            tk10000.setBackground(Color.white);
            con = false;
            fastAmount = "0";
        }
    }//GEN-LAST:event_tk10000MouseClicked

    private void ConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmMouseClicked
        // TODO add your handling code here:
        float f = Float.parseFloat(fastAmount);
        float f2 = Float.parseFloat(Balance);
        float f3 = f2 - f;
        String s = Float.toString(f3);
        String line = null;
        String line2 = null;

        if (f3 >= 0) {
            String pass;
            pass = JOptionPane.showInputDialog(this, "Type your password");
            if (pass.equals(Password)) {

                FileReader fr = null;
                try {
                    fr = new FileReader("src\\Database.csv");
                    BufferedReader br = new BufferedReader(fr);
                    try {
                        while ((line = br.readLine()) != null) {
                            String[] arr = line.split(",");
                            if (AccNo.equals(arr[0]) && Password.equals(arr[1])) {

                                line2 = arr[0] + "," + arr[1] + "," + arr[2] + "," + arr[3] + "," + arr[4] + "," + arr[5] + "," + arr[6] + "," + arr[7] + "," + s;
                                break;
                            }
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    Path path = Paths.get("src\\Database.csv");
                    Charset charset = StandardCharsets.UTF_8;
                    String content = null;
                    try {
                        content = new String(Files.readAllBytes(path), charset);
                    } catch (IOException ex) {
                        Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    content = content.replaceAll(line, line2);
                    try {
                        Files.write(path, content.getBytes(charset));
                    } catch (IOException ex) {
                        Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        fr.close();
                    } catch (IOException ex) {
                        Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                 JOptionPane.showMessageDialog(this,"Your money has been withdrawn");
                
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Wrong password");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Amount, Not enough balance");
        }


    }//GEN-LAST:event_ConfirmMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastCash().setVisible(true);
            }
        });
    }

    public Boolean con = false;
    public int flag = 0;
    public String fastAmount;

    public String AccNo;
    public String Name;
    public String Password;
    public String Balance;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirm;
    protected javax.swing.JLabel accNo;
    private javax.swing.JLabel amount;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    protected javax.swing.JLabel name;
    private javax.swing.JButton tk100;
    private javax.swing.JButton tk1000;
    private javax.swing.JButton tk10000;
    private javax.swing.JButton tk2000;
    private javax.swing.JButton tk500;
    private javax.swing.JButton tk5000;
    // End of variables declaration//GEN-END:variables
}
