/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author Tanvin
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        accNo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ButtonDeposit = new javax.swing.JButton();
        ButtonBalance = new javax.swing.JButton();
        ButtonWithdraw = new javax.swing.JButton();
        ButtonFastCash = new javax.swing.JButton();
        ButtonCngPass = new javax.swing.JButton();
        MiniStateButt = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ATM.gif"))); // NOI18N
        jLabel1.setText("Virtual ATM");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("AlpengeistJF", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome");

        name.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/account.gif"))); // NOI18N
        name.setText("Mr. Borolok");
        name.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Account No:");

        accNo.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        accNo.setForeground(new java.awt.Color(255, 255, 255));
        accNo.setText("12345678910");

        jPanel2.setBackground(new java.awt.Color(24, 78, 99));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(0, 51, 255), new java.awt.Color(0, 51, 255), new java.awt.Color(51, 102, 255)));

        ButtonDeposit.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        ButtonDeposit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/deposit.gif"))); // NOI18N
        ButtonDeposit.setText("Deposit");
        ButtonDeposit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonDeposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonDepositMouseClicked(evt);
            }
        });
        ButtonDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDepositActionPerformed(evt);
            }
        });

        ButtonBalance.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        ButtonBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/balance.gif"))); // NOI18N
        ButtonBalance.setText("Balance");
        ButtonBalance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonBalanceMouseClicked(evt);
            }
        });
        ButtonBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBalanceActionPerformed(evt);
            }
        });

        ButtonWithdraw.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        ButtonWithdraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/withdraw.gif"))); // NOI18N
        ButtonWithdraw.setText("Withdraw");
        ButtonWithdraw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonWithdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonWithdrawMouseClicked(evt);
            }
        });
        ButtonWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonWithdrawActionPerformed(evt);
            }
        });

        ButtonFastCash.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        ButtonFastCash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fastcash.gif"))); // NOI18N
        ButtonFastCash.setText("Fast Cash");
        ButtonFastCash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonFastCash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonFastCashMouseClicked(evt);
            }
        });
        ButtonFastCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFastCashActionPerformed(evt);
            }
        });

        ButtonCngPass.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        ButtonCngPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/changepin.gif"))); // NOI18N
        ButtonCngPass.setText("Change Password");
        ButtonCngPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCngPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCngPassMouseClicked(evt);
            }
        });
        ButtonCngPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCngPassActionPerformed(evt);
            }
        });

        MiniStateButt.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        MiniStateButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/statement.gif"))); // NOI18N
        MiniStateButt.setText("Previous Transaction");
        MiniStateButt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MiniStateButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiniStateButtMouseClicked(evt);
            }
        });
        MiniStateButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiniStateButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ButtonCngPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MiniStateButt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonFastCash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonFastCash, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonBalance))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDeposit)
                    .addComponent(MiniStateButt))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonWithdraw)
                    .addComponent(ButtonCngPass))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("a Astro Space", 0, 14)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logout.gif"))); // NOI18N
        logout.setText("Log Out");
        logout.setName(""); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(logout)
                        .addGap(213, 213, 213)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accNo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accNo)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(logout)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonDepositActionPerformed

    private void ButtonBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonBalanceActionPerformed

    private void ButtonWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonWithdrawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonWithdrawActionPerformed

    private void ButtonFastCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFastCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonFastCashActionPerformed

    private void ButtonCngPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCngPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCngPassActionPerformed

    private void MiniStateButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiniStateButtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MiniStateButtActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        ThankYou ty=new ThankYou();
        
        dispose();
        ty.setVisible(true);     
    }//GEN-LAST:event_logoutMouseClicked

    private void ButtonBalanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonBalanceMouseClicked
        // TODO add your handling code here:
        Balance bal=new Balance();
        bal.setVisible(true);
        bal.AccNo=AccNo;
        bal.Name=Name;
        bal.Password=Password;
        bal.name.setText("Mr. "+Name);
        bal.accNo.setText(AccNo);
        try {
            FileReader fr=new FileReader("src\\Database.csv");
            BufferedReader br=new BufferedReader(fr);
            String line;
            while((line=br.readLine())!=null)
            {   
                String [] arr=line.split(",");
                if(AccNo.equals(arr[0])&&Password.equals(arr[1]))
                {  
                    Balance=arr[8];
                    bal.Balance=Balance;
                    break;
                } 
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_ButtonBalanceMouseClicked

    private void ButtonDepositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonDepositMouseClicked
        // TODO add your handling code here:
        Deposit dep=new Deposit();
        dep.setVisible(true);
        dep.AccNo=AccNo;
        dep.Name=Name;
        dep.Password=Password;
        dep.name.setText("Mr. "+Name);
        dep.accNo.setText(AccNo);
        try {
            FileReader fr=new FileReader("src\\Database.csv");
            BufferedReader br=new BufferedReader(fr);
            String line;
            while((line=br.readLine())!=null)
            {   
                String [] arr=line.split(",");
                if(AccNo.equals(arr[0])&&Password.equals(arr[1]))
                {  
                    Balance=arr[8];
                    dep.Balance=Balance;
                    break;
                } 
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonDepositMouseClicked

    private void ButtonWithdrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonWithdrawMouseClicked
        // TODO add your handling code here:
        Withdraw wit=new Withdraw();
        wit.setVisible(true);
        wit.AccNo=AccNo;
        wit.Name=Name;
        wit.Password=Password;
        wit.name.setText("Mr. "+Name);
        wit.accNo.setText(AccNo);
        try {
            FileReader fr=new FileReader("src\\Database.csv");
            BufferedReader br=new BufferedReader(fr);
            String line;
            while((line=br.readLine())!=null)
            {   
                String [] arr=line.split(",");
                if(AccNo.equals(arr[0])&&Password.equals(arr[1]))
                {  
                    Balance=arr[8];
                    wit.Balance=Balance;
                    break;
                } 
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonWithdrawMouseClicked

    private void ButtonFastCashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonFastCashMouseClicked
        // TODO add your handling code here:
        FastCash fast=new FastCash();
        fast.setVisible(true);
        fast.AccNo=AccNo;
        fast.Name=Name;
        fast.Password=Password;
        fast.name.setText("Mr. "+Name);
        fast.accNo.setText(AccNo);
        try {
            FileReader fr=new FileReader("src\\Database.csv");
            BufferedReader br=new BufferedReader(fr);
            String line;
            while((line=br.readLine())!=null)
            {   
                String [] arr=line.split(",");
                if(AccNo.equals(arr[0])&&Password.equals(arr[1]))
                {  
                    Balance=arr[8];
                    fast.Balance=Balance;
                    break;
                } 
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonFastCashMouseClicked

    private void MiniStateButtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniStateButtMouseClicked
        // TODO add your handling code here:

        // TODO add your handling code here:

        MiniState ms = new MiniState();
        ms.setVisible(true);
        ms.menu=this;
        JLabel name1=ms.GetName();
        name1.setText(Name);
        JLabel accNo1=ms.getAccNo();
        accNo1.setText(AccNo);
        
        
        
        FileReader fr = null;
        try {
            fr = new FileReader("src\\Database.csv");
        }
        catch (FileNotFoundException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
            BufferedReader br=new BufferedReader(fr);
            String line;
        try {
            while((line=br.readLine())!=null)
            {   
                String [] arr=line.split(",");
                if(AccNo.equals(arr[0])&&Password.equals(arr[1]))
                {  
                    Line=line;
                    break;
                } 
            }
        }
        catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        JTable jt = ms.getDataTable();
        String str[] = Line.split(",");
//        for (int i = 0; i < 1; i++) {
//            for (int j = 0; j < jt.getColumnCount(); j++) {
//                jt.setValueAt(str[j], i, j);
//            }
//        }


        jt.setValueAt(str[0], 0, 0);
        jt.setValueAt(str[3], 0, 1);
        jt.setValueAt(str[4], 0, 2);
        jt.setValueAt(str[5], 0, 3);
        jt.setValueAt(str[6], 0, 4);
        jt.setValueAt(str[7], 0, 5);
        jt.setValueAt(str[8], 0, 6);
    }//GEN-LAST:event_MiniStateButtMouseClicked

    private void ButtonCngPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCngPassMouseClicked
        // TODO add your handling code here:
        ChangePassword cng=new ChangePassword();
        cng.setVisible(true);
        cng.AccNo=AccNo;
        cng.Name=Name;
        cng.Password=Password;
        cng.name.setText("Mr. "+Name);
        cng.accNo.setText(AccNo);
    }//GEN-LAST:event_ButtonCngPassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FileNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
             
       
    }
    
    public String Line;
    public  String AccNo;
    public  String Name;
    public  Boolean matched;
    public  String  Password;
    public  String  PinNum;
    public  String  Email;
    public  String  Balance;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBalance;
    private javax.swing.JButton ButtonCngPass;
    private javax.swing.JButton ButtonDeposit;
    private javax.swing.JButton ButtonFastCash;
    private javax.swing.JButton ButtonWithdraw;
    private javax.swing.JButton MiniStateButt;
    protected javax.swing.JLabel accNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logout;
    protected javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
